spring:
  application:
    name: ekart-api-gateway
  profiles:
    active: ${ENV}

  cloud:
    gateway:
      routes:
        - id: product-inner-api
          uri: lb://product-inner-api
          predicates:
            - Path=/products/**
        - id: order-inner-api
          uri: lb://order-inner-api
          predicates:
            - Path=/orders/**
      default-filters:
        - TokenRelay
