spring:
  datasource:
    url: jdbc:mysql://localhost:3306/product

  config:
    import: configserver:http://localhost:9196
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/auth/realms/ekart
